# Generated by Django 4.2.30 on 2026-10-08 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('hostel_type', models.CharField(max_length=32)),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('occupied', models.PositiveIntegerField(default=0)),
                ('warden', models.CharField(blank=True, max_length=128)),
                ('phone', models.CharField(blank=True, max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_code', models.CharField(max_length=32)),
                ('beds', models.PositiveIntegerField(default=4)),
                ('occupied', models.PositiveIntegerField(default=0)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hostel.hostel')),
            ],
            options={
                'unique_together': {('hostel', 'room_code')},
            },
        ),
        migrations.CreateModel(
            name='HostelRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(max_length=32)),
                ('issue', models.TextField()),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Under Review', 'Under Review'), ('Resolved', 'Resolved')], default='Pending', max_length=32)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='hostel.room')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostel_requests', to='school.student')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='RoomStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_students', to='hostel.room')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hostel_room', to='school.student')),
            ],
            options={
                'unique_together': {('room', 'student')},
            },
        ),
    ]
