# Generated by Django 4.2.30 on 2026-10-08 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=128)),
                ('date', models.DateField()),
                ('audience', models.CharField(max_length=64)),
                ('priority', models.CharField(default='Medium', max_length=16)),
                ('pinned', models.BooleanField(default=False)),
                ('views', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-pinned', '-date'],
            },
        ),
    ]
