import { useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Bell, Calendar, Eye, Pin, Plus, Search, Trash2, Edit } from "lucide-react";
import { toast } from "sonner";
import { api, getErrorMessage } from "@/lib/api";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Card, CardContent } from "@/components/ui/card";
import { Textarea } from "@/components/ui/textarea";

type Notice = { id: number; title: string; content: string; author: string; date: string; audience: string; priority: string; pinned: boolean; views: number };
type NoticeDraft = Omit<Notice, "id" | "views">;
const emptyDraft: NoticeDraft = { title: "", content: "", author: "Able God College Administration", date: new Date().toISOString().slice(0, 10), audience: "All", priority: "Medium", pinned: false };
const noticePath = "/notices/notices/";
const rows = (value: Notice[] | { results?: Notice[] }) => Array.isArray(value) ? value : value.results ?? [];

const NoticeSection = () => {
  const client = useQueryClient();
  const { data = [], isLoading, error } = useQuery({ queryKey: ["admin-notices"], queryFn: async () => rows(await api.get<Notice[] | { results?: Notice[] }>(noticePath)) });
  const [search, setSearch] = useState("");
  const [audience, setAudience] = useState("all");
  const [draft, setDraft] = useState<NoticeDraft | null>(null);
  const save = useMutation({ mutationFn: (item: NoticeDraft | (NoticeDraft & { id: number })) => "id" in item ? api.patch(`${noticePath}${item.id}/`, item) : api.post(noticePath, item), onSuccess: () => { void client.invalidateQueries({ queryKey: ["admin-notices"] }); setDraft(null); toast.success("Notice saved"); }, onError: e => toast.error(getErrorMessage(e)) });
  const remove = useMutation({ mutationFn: (id: number) => api.delete(`${noticePath}${id}/`), onSuccess: () => { void client.invalidateQueries({ queryKey: ["admin-notices"] }); toast.success("Notice deleted"); }, onError: e => toast.error(getErrorMessage(e)) });
  const togglePin = (notice: Notice) => save.mutate({ id: notice.id, title: notice.title, content: notice.content, author: notice.author, date: notice.date, audience: notice.audience, priority: notice.priority, pinned: !notice.pinned });
  const filtered = useMemo(() => data.filter(n => (audience === "all" || n.audience === audience) && `${n.title} ${n.content}`.toLowerCase().includes(search.toLowerCase())), [data, audience, search]);
  const submit = () => { if (!draft?.title.trim() || !draft.content.trim()) { toast.error("Enter a title and notice message"); return; } save.mutate(draft); };

  return <div className="space-y-6">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-heading text-xl font-bold">Notice Board</h2><p className="text-sm text-muted-foreground">Manage Able God College announcements</p></div><Button variant="gold" onClick={() => setDraft({ ...emptyDraft })}><Plus className="mr-2 h-4 w-4"/>Create Notice</Button></div>
    <div className="grid grid-cols-2 gap-4 md:grid-cols-4">{[["Notices", data.length, Bell], ["Pinned", data.filter(n => n.pinned).length, Pin], ["High Priority", data.filter(n => n.priority === "High").length, Bell], ["Recorded Views", data.reduce((sum, n) => sum + n.views, 0), Eye]].map(([label, count, Icon]) => <Card key={String(label)}><CardContent className="flex items-center gap-3 p-4"><span className="rounded-lg bg-primary/10 p-2"><Icon className="h-5 w-5 text-primary"/></span><div><p className="text-2xl font-bold">{count}</p><p className="text-xs text-muted-foreground">{label}</p></div></CardContent></Card>)}</div>
    <div className="flex flex-col gap-3 sm:flex-row"><div className="relative flex-1"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground"/><Input className="pl-10" placeholder="Search notices" value={search} onChange={e => setSearch(e.target.value)}/></div><select className="rounded-lg border border-border bg-background px-4 py-2" value={audience} onChange={e => setAudience(e.target.value)}><option value="all">All audiences</option>{["All Students", "All Parents", "Staff Only", "Form 4", "Form 3"].map(a => <option key={a}>{a}</option>)}</select></div>
    {isLoading ? <p className="py-12 text-center text-muted-foreground">Loading notices…</p> : error ? <p className="rounded-xl border border-destructive/30 p-5 text-destructive">Could not load notices: {getErrorMessage(error)}</p> : filtered.length === 0 ? <Card><CardContent className="p-8 text-center text-muted-foreground">No notices have been published yet.</CardContent></Card> : <div className="space-y-3">{filtered.map(n => <Card key={n.id} className={n.pinned ? "border-primary/50" : ""}><CardContent className="flex flex-col justify-between gap-4 p-5 md:flex-row"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h3 className="text-lg font-semibold">{n.title}</h3><span className="rounded bg-secondary px-2 py-0.5 text-xs">{n.priority}</span>{n.pinned && <Pin className="h-4 w-4 text-primary"/>}</div><p className="my-2 text-sm text-muted-foreground">{n.content}</p><div className="flex flex-wrap gap-4 text-xs text-muted-foreground"><span className="flex items-center gap-1"><Calendar className="h-3 w-3"/>{n.date}</span><span>{n.audience}</span><span>{n.views} views</span><span>By {n.author}</span></div></div><div className="flex shrink-0 gap-2"><Button variant="outline" size="icon" aria-label="Toggle pin" onClick={() => togglePin(n)}><Pin className="h-4 w-4"/></Button><Button variant="outline" size="icon" aria-label="Edit notice" onClick={() => setDraft({ ...n })}><Edit className="h-4 w-4"/></Button><Button variant="outline" size="icon" aria-label="Delete notice" disabled={remove.isPending} onClick={() => window.confirm(`Delete “${n.title}”?`) && remove.mutate(n.id)}><Trash2 className="h-4 w-4 text-destructive"/></Button></div></CardContent></Card>)}</div>}
    {draft && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4" onClick={() => setDraft(null)}><div className="max-h-[90vh] w-full max-w-lg space-y-4 overflow-y-auto rounded-xl bg-card p-6" onClick={e => e.stopPropagation()}><h3 className="text-xl font-bold">{"id" in draft ? "Edit Notice" : "Create Notice"}</h3><label className="block text-sm">Title<Input value={draft.title} onChange={e => setDraft({ ...draft, title: e.target.value })}/></label><label className="block text-sm">Content<Textarea rows={5} value={draft.content} onChange={e => setDraft({ ...draft, content: e.target.value })}/></label><div className="grid grid-cols-2 gap-3"><label className="text-sm">Audience<select className="mt-1 w-full rounded-lg border bg-background p-2" value={draft.audience} onChange={e => setDraft({ ...draft, audience: e.target.value })}>{["All", "All Students", "All Parents", "Staff Only", "Form 4", "Form 3"].map(a => <option key={a}>{a}</option>)}</select></label><label className="text-sm">Priority<select className="mt-1 w-full rounded-lg border bg-background p-2" value={draft.priority} onChange={e => setDraft({ ...draft, priority: e.target.value })}>{["High", "Medium", "Low"].map(p => <option key={p}>{p}</option>)}</select></label></div><div className="flex justify-end gap-2"><Button variant="outline" onClick={() => setDraft(null)}>Cancel</Button><Button variant="gold" disabled={save.isPending} onClick={submit}>{save.isPending ? "Saving…" : "Save Notice"}</Button></div></div></div>}
  </div>;
};
export default NoticeSection;
