import { useEffect, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Lock, Mail, Save, User } from "lucide-react";
import { toast } from "sonner";
import { api, clearAuth, getErrorMessage } from "@/lib/api";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

type CurrentUser = { id: number; username: string; email: string; full_name: string; role: string };
const ProfileSection = () => {
  const client = useQueryClient();
  const { data, isLoading, error } = useQuery({ queryKey: ["current-user"], queryFn: () => api.get<CurrentUser>("/auth/me/") });
  const [fullName, setFullName] = useState(""); const [email, setEmail] = useState("");
  const [currentPassword, setCurrentPassword] = useState(""); const [newPassword, setNewPassword] = useState(""); const [confirmPassword, setConfirmPassword] = useState("");
  useEffect(() => { if (data) { setFullName(data.full_name || ""); setEmail(data.email || ""); } }, [data]);
  const saveProfile = useMutation({ mutationFn: () => api.patch("/auth/me/", { full_name: fullName.trim(), email: email.trim() }), onSuccess: () => { void client.invalidateQueries({ queryKey: ["current-user"] }); toast.success("Profile updated"); }, onError: e => toast.error(getErrorMessage(e)) });
  const changePassword = useMutation({ mutationFn: () => api.post("/auth/change-password/", { current_password: currentPassword, new_password: newPassword }), onSuccess: () => { clearAuth(); toast.success("Password changed. Sign in again with your new password."); window.location.assign("/auth"); }, onError: e => toast.error(getErrorMessage(e)) });
  const submitPassword = () => { if (newPassword.length < 8) { toast.error("New password must be at least 8 characters"); return; } if (newPassword !== confirmPassword) { toast.error("New password and confirmation do not match"); return; } changePassword.mutate(); };
  return <div className="space-y-6"><div><h2 className="font-heading text-xl font-bold">My Profile</h2><p className="text-sm text-muted-foreground">Update your account details and password</p></div>{isLoading?<p className="py-8 text-center text-muted-foreground">Loading profile…</p>:error?<p className="text-destructive">Unable to load your account: {getErrorMessage(error)}</p>:<div className="grid gap-6 lg:grid-cols-2"><section className="space-y-4 rounded-xl border bg-card p-6"><h3 className="font-semibold">Account details</h3><div className="flex items-center gap-3 rounded-lg bg-secondary/50 p-3"><User className="h-5 w-5 text-primary"/><div><p className="font-medium">{data?.username}</p><p className="text-xs text-muted-foreground">{data?.role} portal account</p></div></div><label className="block text-sm">Full name<Input autoComplete="name" value={fullName} onChange={e=>setFullName(e.target.value)}/></label><label className="block text-sm">Email address<Input type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><Button variant="gold" disabled={saveProfile.isPending||!fullName.trim()||!email.trim()} onClick={()=>saveProfile.mutate()}><Save className="mr-2 h-4 w-4"/>{saveProfile.isPending?"Saving…":"Save Profile"}</Button></section><section className="space-y-4 rounded-xl border bg-card p-6"><h3 className="flex items-center gap-2 font-semibold"><Lock className="h-4 w-4 text-primary"/>Change password</h3><label className="block text-sm">Current password<Input type="password" autoComplete="current-password" value={currentPassword} onChange={e=>setCurrentPassword(e.target.value)}/></label><label className="block text-sm">New password<Input type="password" autoComplete="new-password" minLength={8} value={newPassword} onChange={e=>setNewPassword(e.target.value)}/></label><label className="block text-sm">Confirm new password<Input type="password" autoComplete="new-password" minLength={8} value={confirmPassword} onChange={e=>setConfirmPassword(e.target.value)}/></label><p className="text-xs text-muted-foreground">Changing your password signs you out of this device.</p><Button variant="gold" disabled={changePassword.isPending||!currentPassword||!newPassword||!confirmPassword} onClick={submitPassword}><Mail className="mr-2 h-4 w-4"/>{changePassword.isPending?"Updating…":"Change Password"}</Button></section></div>}</div>;
};
export default ProfileSection;
