import { useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Plus, Search, Shield, UserPlus, UserX, Edit } from "lucide-react";
import { toast } from "sonner";
import { api, getErrorMessage } from "@/lib/api";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Card, CardContent } from "@/components/ui/card";

type Role = { id: number; name: string; description: string; permissions: string[]; users_count: number };
type Account = { id: number; username: string; email: string; full_name: string; role: number | null; role_name: string; is_active: boolean; date_joined: string };
type AccountDraft = { id?: number; username: string; email: string; full_name: string; role: string; password: string; is_active: boolean };
type RoleDraft = { id?: number; name: string; description: string };
const rows = <T,>(x: T[] | { results?: T[] }) => Array.isArray(x) ? x : x.results ?? [];
const emptyAccounts: Account[] = [];
const emptyRoles: Role[] = [];
const UsersRolesSection = ({ activeSubNav }: { activeSubNav: string }) => {
  const client = useQueryClient();
  const [search, setSearch] = useState("");
  const [accountDraft, setAccountDraft] = useState<AccountDraft | null>(null);
  const [roleDraft, setRoleDraft] = useState<RoleDraft | null>(null);
  const isRoleView = activeSubNav === "roles";
  const accountsQuery = useQuery({ queryKey: ["admin-accounts"], queryFn: async () => rows(await api.get<Account[] | { results?: Account[] }>("/auth/accounts/")) });
  const rolesQuery = useQuery({ queryKey: ["admin-roles"], queryFn: async () => rows(await api.get<Role[] | { results?: Role[] }>("/auth/roles/")) });
  const refresh = () => { void client.invalidateQueries({ queryKey: ["admin-accounts"] }); void client.invalidateQueries({ queryKey: ["admin-roles"] }); };
  const saveAccount = useMutation({ mutationFn: (d: AccountDraft) => { const payload = { username: d.username, email: d.email, full_name: d.full_name, role: Number(d.role), is_active: d.is_active, ...(d.password ? { password: d.password } : {}) }; return d.id ? api.patch(`/auth/accounts/${d.id}/`, payload) : api.post("/auth/accounts/", payload); }, onSuccess: () => { refresh(); setAccountDraft(null); toast.success("Account saved"); }, onError: e => toast.error(getErrorMessage(e)) });
  const saveRole = useMutation({ mutationFn: (d: RoleDraft) => d.id ? api.patch(`/auth/roles/${d.id}/`, d) : api.post("/auth/roles/", { ...d, permissions: [] }), onSuccess: () => { refresh(); setRoleDraft(null); toast.success("Role saved"); }, onError: e => toast.error(getErrorMessage(e)) });
  const deactivate = async (account: Account) => { if (!window.confirm(`Deactivate ${account.full_name || account.username}? The account and its school records will be kept.`)) return; try { await api.delete(`/auth/accounts/${account.id}/`); refresh(); toast.success("Account deactivated"); } catch (e) { toast.error(getErrorMessage(e)); } };
  const accounts = accountsQuery.data ?? emptyAccounts; const roles = rolesQuery.data ?? emptyRoles;
  const filtered = useMemo(() => accounts.filter(a => `${a.full_name} ${a.username} ${a.email} ${a.role_name}`.toLowerCase().includes(search.toLowerCase())), [accounts, search]);
  return <div className="space-y-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-heading text-xl font-bold">Users & Roles</h2><p className="text-sm text-muted-foreground">Manage real portal accounts and role definitions</p></div>{isRoleView?<Button variant="gold" onClick={()=>setRoleDraft({name:"",description:""})}><Plus className="mr-2 h-4 w-4"/>Add Role</Button>:<Button variant="gold" onClick={()=>setAccountDraft({username:"",email:"",full_name:"",role:"",password:"",is_active:true})}><UserPlus className="mr-2 h-4 w-4"/>Add Account</Button>}</div>
    {accountsQuery.error||rolesQuery.error?<p className="rounded-xl border border-destructive/30 p-5 text-destructive">Could not load account data: {getErrorMessage(accountsQuery.error||rolesQuery.error)}</p>:isRoleView?<>{rolesQuery.isLoading?<p className="py-8 text-center text-muted-foreground">Loading roles…</p>:<div className="grid gap-4 md:grid-cols-2">{roles.map(role=><Card key={role.id}><CardContent className="flex items-start justify-between p-5"><div><h3 className="font-semibold"><Shield className="mr-2 inline h-4 w-4 text-primary"/>{role.name}</h3><p className="mt-1 text-sm text-muted-foreground">{role.description||"No role description"}</p><p className="mt-3 text-xs text-muted-foreground">{role.users_count} linked account(s)</p></div><Button variant="outline" size="icon" aria-label={`Edit ${role.name} role`} onClick={()=>setRoleDraft({id:role.id,name:role.name,description:role.description})}><Edit className="h-4 w-4"/></Button></CardContent></Card>)}{roles.length===0&&<p className="col-span-full py-8 text-center text-muted-foreground">No roles have been configured.</p>}</div>}</>:<><div className="relative"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground"/><Input className="pl-10" placeholder="Search accounts" value={search} onChange={e=>setSearch(e.target.value)}/></div>{accountsQuery.isLoading?<p className="py-8 text-center text-muted-foreground">Loading accounts…</p>:<div className="overflow-x-auto rounded-xl border bg-card"><table className="w-full min-w-[700px]"><thead className="bg-secondary/50"><tr>{["Name", "Email / username", "Role", "Status", "Created", "Actions"].map(x=><th key={x} className="px-4 py-3 text-left text-sm">{x}</th>)}</tr></thead><tbody>{filtered.map(a=><tr key={a.id} className="border-t"><td className="px-4 py-3 font-medium">{a.full_name||a.username}</td><td className="px-4 py-3">{a.email||a.username}</td><td className="px-4 py-3">{a.role_name||"Unassigned"}</td><td className="px-4 py-3">{a.is_active?"Active":"Inactive"}</td><td className="px-4 py-3">{new Date(a.date_joined).toLocaleDateString()}</td><td className="px-4 py-3"><Button variant="outline" size="icon" aria-label="Edit account" onClick={()=>setAccountDraft({id:a.id,username:a.username,email:a.email,full_name:a.full_name,role:a.role?String(a.role):"",password:"",is_active:a.is_active})}><Edit className="h-4 w-4"/></Button>{a.is_active&&<Button className="ml-2" variant="outline" size="icon" aria-label="Deactivate account" onClick={()=>void deactivate(a)}><UserX className="h-4 w-4 text-destructive"/></Button>}</td></tr>)}{filtered.length===0&&<tr><td colSpan={6} className="p-8 text-center text-muted-foreground">No accounts found.</td></tr>}</tbody></table></div>}</>}
    {accountDraft&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4" onClick={()=>setAccountDraft(null)}><div className="max-h-[90vh] w-full max-w-md space-y-4 overflow-y-auto rounded-xl bg-card p-6" onClick={e=>e.stopPropagation()}><h3 className="text-xl font-bold">{accountDraft.id?"Edit Account":"Create Account"}</h3>{(["full_name","username","email"] as const).map(k=><label key={k} className="block text-sm capitalize">{k.replace("_"," ")}<Input value={accountDraft[k]} onChange={e=>setAccountDraft({...accountDraft,[k]:e.target.value})}/></label>)}<label className="block text-sm">Role<select className="mt-1 w-full rounded-lg border bg-background p-2" value={accountDraft.role} onChange={e=>setAccountDraft({...accountDraft,role:e.target.value})}><option value="">Select role</option>{roles.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label>{!accountDraft.id&&<label className="block text-sm">Initial password<Input type="password" minLength={8} value={accountDraft.password} onChange={e=>setAccountDraft({...accountDraft,password:e.target.value})}/></label>}<label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={accountDraft.is_active} onChange={e=>setAccountDraft({...accountDraft,is_active:e.target.checked})}/>Account active</label><div className="flex justify-end gap-2"><Button variant="outline" onClick={()=>setAccountDraft(null)}>Cancel</Button><Button variant="gold" disabled={saveAccount.isPending||!accountDraft.username||!accountDraft.role||(!accountDraft.id&&accountDraft.password.length<8)} onClick={()=>saveAccount.mutate(accountDraft)}>{saveAccount.isPending?"Saving…":"Save Account"}</Button></div></div></div>}
    {roleDraft&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4" onClick={()=>setRoleDraft(null)}><div className="w-full max-w-md space-y-4 rounded-xl bg-card p-6" onClick={e=>e.stopPropagation()}><h3 className="text-xl font-bold">{roleDraft.id?"Edit Role":"Add Role"}</h3><label className="block text-sm">Role name<Input value={roleDraft.name} onChange={e=>setRoleDraft({...roleDraft,name:e.target.value})}/></label><label className="block text-sm">Description<textarea className="mt-1 min-h-24 w-full rounded-lg border bg-background p-2" value={roleDraft.description} onChange={e=>setRoleDraft({...roleDraft,description:e.target.value})}/></label><div className="flex justify-end gap-2"><Button variant="outline" onClick={()=>setRoleDraft(null)}>Cancel</Button><Button variant="gold" disabled={saveRole.isPending||!roleDraft.name.trim()} onClick={()=>saveRole.mutate(roleDraft)}>Save Role</Button></div></div></div>}
  </div>;
};
export default UsersRolesSection;
