# Generated by Django 4.2.30 on 2026-10-08 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=32, unique=True)),
                ('route_name', models.CharField(max_length=128)),
                ('driver', models.CharField(max_length=128)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('capacity', models.PositiveIntegerField(default=45)),
                ('students', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(default='Active', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('stops', models.JSONField(default=list)),
                ('departure_am', models.TimeField(blank=True, null=True)),
                ('departure_pm', models.TimeField(blank=True, null=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='transport.bus')),
            ],
        ),
    ]
